name: gen_bind
on:
  push:
    paths:
      - "onnxruntime-sys/build.rs"
      - ".github/workflows/gen_bind.yaml"
      - ".github/actions/auto_gen_bind_pr/action.yaml"
jobs:
  generate_bind:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            triple: aarch64-unknown-linux-gnu
          - os: windows-latest
            triple: x86_64-pc-windows-msvc
          - os: windows-latest
            triple: x86_64-pc-windows-msvc
            additional_features: directml
          - os: windows-latest
            triple: i686-pc-windows-msvc
          - os: macos-latest
            triple: x86_64-apple-darwin
          - os: macos-latest
            triple: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: ./.github/actions/auto_gen_bind_pr
        with:
          triple: ${{ matrix.triple }}
          additional_features: ${{ matrix.additional_features }}
